Repository upfluence/oss, pull requests merged in 2022-05, with the labels that each got.

#133 Add new color pallet
  less/core-v2/_all.less
  less/core-v2/_colors.less
  less/upfluence-oss.less
Labels: reviewed/needs-work

#134 Add doc for new color pallet
  less/core-v2/_colors.stories.mdx
Labels: reviewed/ready-to-merge

#135 Added: box-shadow, backdrop & border-radius vars
  less/core-v2/_all.less
  less/core-v2/_variables.less
Labels: reviewed/needs-review

#137 Fix value for box-shadow-lg var
  less/core-v2/_variables.less
Labels: reviewed/ready-to-merge

#136 docs/colors: loop over the available tokens for doc generation
  less/core-v2/_colors.stories.mdx
Labels: reviewed/ready-to-merge

#138 Add docs for core-v2/_variables
  less/core-v2/_variables.stories.mdx
Labels: reviewed/ready-to-merge
